#include "../../ADT/stackDraf.h"
#include "../../ADT/listdinKicauan.h"
#include "../../ADT/ListDinOfUtas.h"
#include "../../ADT/liststatikpengguna.h"
#include "../../ADT/friends.h"
#include "../../ADT/pengguna.h"
#include "../../ADT/prioqueue.h"
#include "../../ADT/wordmachine.h"
#include "../../ADT/permintaan_pertemanan.h"

StackDraf progStackDraf[20];
ListPengguna progListPengguna;
Draf progDraf;
ListDinKicauan progListDinKicau;
Kicauan progKicauan;
ListUtas progListDinUtas;
Utas progUtas;
Friends progFriends;
int progIdPengguna;
Queue progQueue[20];
